### ISSUE TITLE
如果我想将模型更改为baichuan2-7b-chat，需要做哪些方面的变动？

### ISSUE THREAD

**Issue by IT-five** [GanjinZero/RRHF#52]

**Comment by GanjinZero** [comment]
换一个load model就行了？

**Comment by GanjinZero** [comment]
tokenizer可能也需要注意下有没有什么区别

**Comment by IT-five** [comment]
> 什么

感谢您的回复，还有一个问题请教一下：
```
--fsdp "full_shard auto_wrap" \
 --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
```
这两行的代码作用是什么，LlamaDecoderLayer适配于Baichuan吗，我没有找到这个源代码

**Comment by GanjinZero** [comment]
https://huggingface.co/baichuan-inc/Baichuan2-7B-Base/blob/main/modeling_baichuan.py 你填DecoderLayer就行吧

**Comment by IT-five** [comment]
> https://huggingface.co/baichuan-inc/Baichuan2-7B-Base/blob/main/modeling_baichuan.py 你填DecoderLayer就行吧

感谢您的回复，这个问题我已经解决，但是在run的时候报错:
```
Traceback (most recent call last):
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 345, in <module>
Traceback (most recent call last):
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 345, in <module>
    train()
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 339, in train
    train()
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 339, in train
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 284, in compute_loss
Traceback (most recent call last):
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 345, in <module>
    loss = self.compute_loss(model, inputs)
  File "/mnt/workspace/rrhf/RRHF/train_baichuan2_prompt.py", line 284, in compute_loss
    logits = F.log_softmax(logits, dim=-1)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 1945, in log_softmax
    ret = input.log_softmax(dim)
AttributeError:     'dict' object has no attribute 'log_softmax'train()
```
`train_baichuan2_prompt.py`就是将`train_alpaca_prompt.py`进行改名，其他地方并未改动
